name: nope_excuse_generator
description: A viral excuse generator app - tap to get funny excuses for skipping plans!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  flutter_animate: ^4.2.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/excuses.json 